### ISSUE TITLE
Can I use Pro Micro instead of Adafruit ItsyBitsy RP2040

### ISSUE THREAD

**Issue by nguyenhaiduc06** [somepin/qalble#1]

**Comment by somepin** [comment]
Hi, Pro Micro and variants (Elite-C, nice!nano, etc.) are not compatible since they have a different pinout than ItsyBitsys.

![pro_micro_pinout](https://user-images.githubusercontent.com/79652090/153765371-94b7385e-966f-44c2-ba9e-89a7ee2a6a53.jpg)

![adafruit_products_itsybitsy-rp2040-pins](https://user-images.githubusercontent.com/79652090/153765377-cb3502df-bb8d-466f-abf4-f8070af3d3bf.png)
